export const SUPPORTED_LANGUAGES = [
  { value: 'javascript', label: 'JavaScript' },
  { value: 'typescript', label: 'TypeScript' },
  { value: 'python', label: 'Python' },
  { value: 'java', label: 'Java' },
  { value: 'csharp', label: 'C#' },
  { value: 'go', label: 'Go' },
  { value: 'rust', label: 'Rust' },
  { value: 'html', label: 'HTML' },
  { value: 'css', label: 'CSS' },
  { value: 'vue', label: 'Vue' },
  { value: 'svelte', label: 'Svelte' },
  { value: 'sql', label: 'SQL' },
  { value: 'shell', label: 'Shell Script' },
  { value: 'powershell', label: 'Powershell' },
  { value: 'terminal', label: 'Terminal' },
  { value: 'json', label: 'JSON' },
  { value: 'markdown', label: 'Markdown' },
  { value: 'ruby', label: 'Ruby' },
  { value: 'php', label: 'PHP' },
  { value: 'cpp', label: 'C++' },
  { value: 'c', label: 'C' },
  { value: 'unrealscript', label: 'Unreal Engine' },
  { value: 'dazscript', label: 'Daz Script' },
  { value: 'plaintext', label: 'Plain Text' },
];
